"""Strict exact answer parsing and additive teacher-forced evidence."""

from pathlib import Path

import pytest
import torch
from pydantic import ValidationError

from flyrl.babi_generation import Generation
from flyrl.babi_learning import BabiExample, make_batch
from flyrl.babi_metrics import evaluate_nll, score_prediction, validate_answer_encoding
from flyrl.bpe_tokenizer import BPETokenizer, restore_tokenizer
from flyrl.language_data import CorpusError
from tests.test_babi_learning import examples, make_learner


@pytest.fixture
def tokenizer() -> BPETokenizer:
    return restore_tokenizer(
        Path("data/tinystories_quality/tokenizer.json").read_text()
    )


@pytest.mark.parametrize(
    ("text", "terminated", "correct"),
    [
        (" bathroom", True, True),
        ("bathroom", True, False),
        ("  bathroom", True, False),
        (" Bathroom", True, False),
        (" bathroom ", True, False),
        (" bathroom\r", True, False),
        (" bathroom", False, False),
        (" bathroom extra", True, False),
        ("", True, False),
    ],
)
def test_exact_parser_is_literal(
    tokenizer: BPETokenizer, text: str, *, terminated: bool, correct: bool
) -> None:
    # Given: generated bytes with independently recorded termination.
    ids = tuple(tokenizer.encode(text, add_special_tokens=False).ids)
    generated = Generation(
        example_id="x", generated_ids=(*ids, 199) if terminated else ids
    )
    # When: only pre-terminator generated IDs are decoded.
    result = score_prediction(
        generated,
        "bathroom",
        lambda tokens: tokenizer.decode(list(tokens), skip_special_tokens=False),
    )
    # Then: no normalization, extraction or unterminated success is possible.
    assert result.correct is correct
    assert result.gold_answer == "bathroom"
    assert result.generated_ids == generated.generated_ids


def test_teacher_forced_evidence_short_batch_and_equal_question_mean() -> None:
    # Given: three questions, with batch size two and unequal answer lengths.
    learner = make_learner()
    data = examples()
    batch = make_batch(data, learner.config.context)
    logits = learner.model.forward(torch.tensor(batch.inputs))
    losses = torch.nn.functional.cross_entropy(
        logits.reshape(-1, 4096),
        torch.tensor(batch.targets).flatten(),
        reduction="none",
    ).reshape(3, -1)
    sums = tuple(float(row.double().sum().item()) for row in losses)
    # When: evaluation includes the final one-question batch.
    metrics = evaluate_nll(learner.model, data)
    # Then: additive token evidence and equal-question NLL match independent CE.
    assert tuple(row.example_id for row in metrics.per_question) == ("a", "b", "c")
    assert tuple(row.count for row in metrics.per_question) == (2, 3, 2)
    assert tuple(row.loss_sum for row in metrics.per_question) == pytest.approx(sums)
    assert metrics.loss_sum == pytest.approx(sum(sums))
    assert metrics.count == 7
    assert metrics.nll == pytest.approx((sums[0] / 2 + sums[1] / 3 + sums[2] / 2) / 3)


@pytest.mark.parametrize(
    "gold", ["bathroom", "bedroom", "garden", "hallway", "kitchen", "office"]
)
def test_answer_encoding_validation(tokenizer: BPETokenizer, gold: str) -> None:
    # Given: the actual committed tokenizer, encoding the answer separately.
    answer = tuple(tokenizer.encode(f" {gold}\n", add_special_tokens=False).ids)
    example = BabiExample(example_id="x", prompt_ids=(10,), answer_ids=answer)
    # When: caller binds the core token example to its decoded gold label.
    validate_answer_encoding(
        example,
        gold,
        lambda tokens: tokenizer.decode(list(tokens), skip_special_tokens=False),
    )
    # Then: all six fixed encodings include LF, with only hallway using three targets.
    assert len(answer) == (3 if gold == "hallway" else 2)
    assert answer[-1] == 199


@pytest.mark.parametrize("gold", ["Bathroom", " bathroom", "bathroom ", "", "attic"])
def test_malformed_gold_rejected(tokenizer: BPETokenizer, gold: str) -> None:
    # Given/When/Then: malformed decoded labels are errors, never normalized labels.
    with pytest.raises(CorpusError):
        _ = score_prediction(
            Generation(example_id="x", generated_ids=(199,)),
            gold,
            lambda tokens: tokenizer.decode(list(tokens)),
        )


def test_mismatched_answer_encoding_and_empty_evaluation_rejected(
    tokenizer: BPETokenizer,
) -> None:
    # Given: tokens for a different answer than the supplied gold.
    example = BabiExample(
        example_id="x",
        prompt_ids=(10,),
        answer_ids=tuple(tokenizer.encode(" kitchen\n", add_special_tokens=False).ids),
    )
    # When/Then: decoded labels must match, and evaluation requires evidence.
    with pytest.raises(CorpusError):
        validate_answer_encoding(
            example, "bathroom", lambda tokens: tokenizer.decode(list(tokens))
        )
    with pytest.raises(CorpusError):
        _ = evaluate_nll(make_learner().model, ())


@pytest.mark.parametrize("ids", [(), (2811, 199, 199), (199, 20), (20,) * 9, (-1,)])
def test_impossible_generation_evidence_rejected(ids: tuple[int, ...]) -> None:
    # Given: empty, post-stop, over-budget, or out-of-vocabulary evidence.
    # When/Then: the immutable generation boundary rejects impossible records.
    with pytest.raises(ValidationError):
        _ = Generation(example_id="x", generated_ids=ids)
