"""Task 1 data boundary, unrestricted evidence evaluation and frozen finalization."""

from dataclasses import dataclass
from pathlib import Path

from flyrl.babi_checkpoint import Checkpoints, publish
from flyrl.babi_data import ANSWER_IDS, BabiError, load_tokenizer
from flyrl.babi_generation import BabiPrompt, greedy_generate
from flyrl.babi_learning import BabiLearner
from flyrl.babi_metrics import evaluate_nll, score_prediction, validate_answer_encoding
from flyrl.babi_pilot_schema import (
    Evaluation,
    PublishedPrediction,
    Report,
    Selection,
    Validation,
    baselines,
    examples,
    select_update,
)
from flyrl.babi_protocol import (
    NOVEL_COUNT,
    PANEL_FACTS,
    PANEL_SIZE,
    BabiProtocol,
    code_identity,
    runtime_identity,
)
from flyrl.babi_recovery import (
    Restoration,
    capture_state,
    record_event,
    seal_artifacts,
)
from flyrl.babi_recovery_validation import EvaluationContext, evaluation
from flyrl.babi_storage import Split, TrainValid, load_test, load_train_valid
from flyrl.bpe_tokenizer import BPETokenizer
from flyrl.connectome import Graph, load_graph
from flyrl.language_runtime import graph_fingerprint
from scripts.connectome_source import file_digest


@dataclass(frozen=True, slots=True)
class Experiment:
    """Read-only experiment dependencies; mutable learning is owned by BabiLearner."""

    protocol: BabiProtocol
    output: Path
    graph: Graph
    corpus: TrainValid
    tokenizer: BPETokenizer

    @classmethod
    def open(cls, protocol: BabiProtocol, output: Path) -> "Experiment":
        """Authenticate train/validation, graph, code and runtime without test I/O."""
        suffix = "npz" if protocol.profile == "quality" else "json"
        corpus = protocol.corpus
        if (
            file_digest(protocol.graph.path) != protocol.graph.sha256
            or file_digest(corpus.path / f"train_valid.{suffix}")
            != corpus.train_valid_sha256
            or code_identity() != protocol.code
            or runtime_identity(protocol.config.device) != protocol.runtime
        ):
            raise BabiError(reason="Protocol artifact/code/runtime identity mismatch")
        graph = load_graph(protocol.graph.path)
        selected = (
            load_train_valid(corpus.path)
            if protocol.profile == "quality"
            else TrainValid.model_validate_json(
                (corpus.path / "train_valid.json").read_bytes()
            )
        )
        if (
            graph_fingerprint(graph) != protocol.graph.fingerprint
            or (len(graph.node_ids), graph.source.size)
            != (protocol.graph.nodes, protocol.graph.edges)
            or selected.fingerprint != corpus.train_valid_fingerprint
            or (len(selected.train.questions), len(selected.valid.questions))
            != corpus.counts[:2]
        ):
            raise BabiError(reason="Protocol graph/split identity mismatch")
        tokenizer = load_tokenizer(corpus.path / "tokenizer.json")
        instance = cls(protocol, output, graph, selected, tokenizer)
        for split in (selected.train, selected.valid):
            for q, example in zip(
                split.questions, examples(split.questions), strict=True
            ):
                validate_answer_encoding(example, q.answer, instance.decode)
                if (
                    len(example.prompt_ids) + len(example.answer_ids) - 1
                    > protocol.config.context
                ):
                    raise BabiError(reason="Protocol sequence overflow")
        return instance

    def decode(self, ids: tuple[int, ...]) -> str:
        """Decode generated bytes literally, including special-token representation."""
        return self.tokenizer.decode(list(ids), skip_special_tokens=False)

    @property
    def checkpoints(self) -> Checkpoints:
        """Bind the stable source-ordered training IDs to every transaction."""
        return Checkpoints(
            self.output,
            self.protocol,
            tuple(e.example_id for e in examples(self.corpus.train.questions)),
        )

    def evaluate(
        self,
        learner: BabiLearner,
        split: Split,
        *,
        removed: bool = False,
        checkpoint_hash: str = "0" * 64,
    ) -> Evaluation:
        """Publish full-vocabulary greedy answers and equal-question additive NLL."""
        data = examples(split.questions, removed=removed)
        generated = greedy_generate(
            learner.model,
            tuple(
                BabiPrompt(example_id=e.example_id, prompt_ids=e.prompt_ids)
                for e in data
            ),
        )
        rows: list[PublishedPrediction] = []
        for q, generation in zip(split.questions, generated, strict=True):
            scored = score_prediction(generation, q.answer, self.decode)
            rows.append(
                PublishedPrediction(
                    example_id=scored.example_id,
                    generated_ids=scored.generated_ids,
                    terminated=scored.terminated,
                    decoded_answer=scored.decoded_answer,
                    gold_answer=scored.gold_answer,
                    exact=scored.correct,
                    episode_id=q.episode_id,
                    question_line=q.question_line,
                    removed_line_ids=q.removed_line_ids if removed else (),
                    checkpoint_sha256=checkpoint_hash,
                )
            )
        return Evaluation(
            predictions=tuple(rows), answer_nll=evaluate_nll(learner.model, data)
        )

    def validate(self, learner: BabiLearner) -> Validation:
        """Persist full milestone evidence before its checkpoint transaction."""
        result = self.evaluate(learner, self.corpus.valid)
        publish(self.output / f"validation-{learner.updates:06d}.json", result)
        return Validation(
            update=learner.updates,
            correct=result.correct,
            questions=len(result.predictions),
            nll=result.answer_nll.nll,
        )

    def memorization_panel(self) -> Split:
        """Pick the first two source-ordered two-fact prompts per answer, exactly 12."""
        selected = tuple(
            q
            for answer in ANSWER_IDS
            for q in tuple(
                q
                for q in self.corpus.train.questions
                if q.answer == answer and len(q.facts) == PANEL_FACTS
            )[:2]
        )
        if len(selected) != PANEL_SIZE:
            raise BabiError(reason="SANITY_FAILED: incomplete memorization panel")
        return Split(
            questions=tuple(
                sorted(selected, key=lambda q: (q.episode_id, q.question_line))
            )
        )

    def finish(self, learner: BabiLearner, history: tuple[Validation, ...]) -> Report:
        """Freeze selection before test access; evaluate both conditions, no tuning."""
        if (
            learner.updates != self.protocol.updates
            or tuple(v.update for v in history) != self.protocol.milestones
        ):
            raise BabiError(reason="Selection requires completed frozen budget")
        selected = select_update(history)
        manifest = self.checkpoints.manifest(selected)
        selection = Selection(
            protocol_sha256=self.protocol.sha256,
            update=selected,
            checkpoint_sha256=manifest.checkpoint_sha256,
            validation=history,
        )
        publish(self.output / "selection.json", selection)
        record_event(self.output, self.protocol, "selection_frozen")
        _ = self.checkpoints.load(learner, selected)
        training_ids = tuple(
            item.example_id for item in examples(self.corpus.train.questions)
        )
        before = capture_state(learner, training_ids, self.protocol.next_lr(selected))
        _ = self.checkpoints.load(learner, selected)
        after = capture_state(learner, training_ids, self.protocol.next_lr(selected))
        if before != after:
            raise BabiError(reason="Selected checkpoint restoration mismatch")
        suffix = "npz" if self.protocol.profile == "quality" else "json"
        record_event(self.output, self.protocol, "test_opened")
        if (
            file_digest(self.protocol.corpus.path / f"test.{suffix}")
            != self.protocol.corpus.test_sha256
        ):
            raise BabiError(reason="Official test identity mismatch")
        test = (
            load_test(self.protocol.corpus.path)
            if self.protocol.profile == "quality"
            else Split.model_validate_json(
                (self.protocol.corpus.path / "test.json").read_bytes()
            )
        )
        if len(test.questions) != self.protocol.corpus.counts[2]:
            raise BabiError(reason="Official test count mismatch")
        evaluations: list[Evaluation] = []
        replays: list[tuple[PublishedPrediction, ...]] = []
        for removed in (False, True):
            path = self.output / ("removed.json" if removed else "ordinary.json")
            result = (
                Evaluation.model_validate_json(path.read_bytes())
                if path.exists()
                else self.evaluate(
                    learner,
                    test,
                    removed=removed,
                    checkpoint_hash=selection.checkpoint_sha256,
                )
            )
            _ = evaluation(
                result,
                test.questions,
                EvaluationContext(selection.checkpoint_sha256, removed, self.decode),
            )
            publish(path, result)
            _ = self.checkpoints.load(learner, selected)
            replay = self.evaluate(
                learner,
                Split(questions=test.questions[:32]),
                removed=removed,
                checkpoint_hash=selection.checkpoint_sha256,
            )
            if replay.predictions != result.predictions[:32]:
                raise BabiError(reason="Selected checkpoint replay mismatch")
            evaluations.append(result)
            replays.append(replay.predictions)
        ordinary, removed_result = evaluations
        publish(
            self.output / "restoration.json",
            Restoration(
                checkpoint_sha256=selection.checkpoint_sha256,
                runtime=self.protocol.runtime,
                before=before,
                after=after,
                ordinary=replays[0],
                removed=replays[1],
            ),
        )
        prompts = {q.prompt_hash for q in self.corpus.train.questions}
        novel = tuple(
            p
            for q, p in zip(test.questions, ordinary.predictions, strict=True)
            if q.prompt_hash not in prompts
        )
        if self.protocol.profile == "quality" and len(novel) != NOVEL_COUNT:
            raise BabiError(reason="Official train-novel diagnostic count mismatch")
        report = Report(
            profile=self.protocol.profile,
            selection=selection,
            ordinary=ordinary,
            removed=removed_result,
            train_novel_correct=sum(p.correct for p in novel),
            train_novel_questions=len(novel),
            baseline_valid=baselines(
                self.corpus.train.questions, self.corpus.valid.questions
            ),
            baseline_test=baselines(self.corpus.train.questions, test.questions),
            splits=(self.corpus.train.report, self.corpus.valid.report, test.report),
        )
        publish(self.output / "report.json", report)
        publish(self.output / "decision.json", report.decision)
        record_event(self.output, self.protocol, "completed")
        _ = seal_artifacts(self.output, self.protocol)
        return report
